'use server';

import { GoogleGenerativeAI } from '@google/generative-ai';
import { VideoConfig } from '../../remotion/types/video';

// Allow API key to be set via environment variable
const API_KEY = process.env.GOOGLE_API_KEY;

export async function generateVideoConfig(topic: string, theme: string): Promise<VideoConfig | null> {
    if (!API_KEY) {
        console.error('GOOGLE_API_KEY is not set');
        // Return mock data for demonstration if no key is present
        return {
            title: `AI Generated: ${topic}`,
            themeLabel: 'AI Demo',
            themeId: theme as any,
            duration: 15,
            sections: [
                {
                    type: 'hook',
                    startSec: 0,
                    endSec: 3,
                    onScreenText: `Start with ${topic}!`,
                },
                {
                    type: 'keypoint',
                    startSec: 3,
                    endSec: 10,
                    onScreenText: 'AI says this is important.',
                },
                {
                    type: 'conclusion',
                    startSec: 10,
                    endSec: 15,
                    onScreenText: 'Summary here.',
                }
            ],
            disclaimer: 'Generated by AI (Mock)',
        };
    }

    const genAI = new GoogleGenerativeAI(API_KEY);
    const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash', generationConfig: { responseMimeType: "application/json" } });

    const prompt = `
    You are a professional medical video producer. Create a JSON configuration for a YouTube Shorts video about "${topic}".
    Target audience: General public. Tone: Professional yet engaging.
    Duration: Approx 30-45 seconds.
    Theme: ${theme}.

    Output Format (JSON):
    {
      "title": "Video Title",
      "themeLabel": "Category Label (e.g. Pathology)",
      "themeId": "${theme}",
      "duration": number (total seconds),
      "sections": [
        { "type": "hook", "startSec": 0, "endSec": 3, "onScreenText": "Hook text" },
        { "type": "keypoint", "startSec": 3, "endSec": 8, "onScreenText": "Point 1 explanations", "highlight": { "x": 500, "y": 900, "radius": 100 } },
        { "type": "quiz", "startSec": 8, "endSec": 13, "question": "Quiz Question?", "choices": ["A", "B", "C"], "answer": "A", "answerSoundEffect": "audio/se/quiz_correct.mp3" },
        { "type": "conclusion", "startSec": 13, "endSec": 18, "onScreenText": "Conclusion text" }
      ],
      "disclaimer": "Medical output generated by AI"
    }
    
    Ensure timing is continuous. Add "soundEffect" property to sections if appropriate (e.g. "audio/se/pop.mp3").
    `;

    try {
        const result = await model.generateContent(prompt);
        const responseProxy = result.response;
        const jsonString = responseProxy.text();
        const videoConfig = JSON.parse(jsonString) as VideoConfig;
        return videoConfig;
    } catch (error) {
        console.error('AI Generation Failed:', error);
        return null;
    }
}
